### ISSUE TITLE
Rename app.*

### ISSUE THREAD

**Issue by thheller** [jacekschae/shadow-re-frame#2]
This is probably one of the things I hate most about templates. Some template way back when decided to create a `.core` namespace and now everything does it. It is usually a terrible naming scheme and should be removed.

In the JVM world everything should technically be namespaced to something unique. Most commonly the reverse domain name notation is used so `app.something.shadow-cljs.org` becomes `org.shadow-cljs.something.app`. The TLD part somehow got lost in the CLJ world but that is fine as long as everything still picks a unique prefix.

The notion that something must be unique on the classpath somehow gets lost when using generic things like `app.*` IMHO. While keeping the classpath clean is not as important for CLJS it still applies when building libraries.  

YMMV and it is fine if you want to keep the `app.*` for this template since its meant to be cloned anyways and having the user input a name is not as easy.

**Comment by jacekschae** [comment]
@thheller 

> There are only two hard things in Computer Science: cache invalidation and naming things.
> -- Phil Karlton

That's the reason why I used `app` - when the template is cloned/forked then you can rename to this your needs. Maybe it would be worth to add this to README. We could call it `shadow-re-frame` instead of `app`, but then it will be the same thing. I believe that `app` is pretty general and universal even when someone decides not to rename it.

What else would you propose instead of `app`? I'm open for ideas and changing things.

**Comment by thheller** [comment]
I guess `app` is the most useful name for this. Can't think of anything else either.
